---
all:
  vars:
    ansible_user: root
    ansible_python_interpreter: /usr/bin/python3
  children:
    postgres_server:
      hosts:
        "10.85.10.241":
    postgres_clients:
      hosts:
        localhost:
          ansible_connection: local
          ansible_become_pass: "{{ localhost_sudo_pass }}"
        "10.85.10.241":
        "10.85.10.238":
